name: Build Application

on:
  push:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout del código
        uses: actions/checkout@v3

      - name: 🔨 Build de la aplicación
        run: npm ci --omit=dev && npm run build

      - name: 🔨 Build de la imagen Docker
        run: docker build --build-arg APP_NAME=${{ env.APP_NAME }} -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:latest .
