name: Linting Code

on:
  push:
    branches:
      - master
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout code
        uses: actions/checkout@v3

      - name: 🔧 Install dependencies
        run: |
          npm install  # o el gestor de dependencias que uses

      - name: 📝 Run linter
        run: |
          npm run lint  # Aquí ejecutas tu linter

      - name: ✨ Format code
        run: |
          npm run format
