name: CI/CD Pipeline for My App

on:
  push:
    branches:
      - master
      - develop

jobs:
  # Job de Linter
  lint:
    uses: ./lint.yml

  # Job de Build
  build:
    needs: lint
    uses: ./build.yml

  # Job de Security Scan
  security_scan:
    needs: build
    uses: ./security_scan.yml

  # Job de Deploy
  deploy:
    needs: security_scan
    uses: ./deploy.yml
