name: Security Scan for Docker Image

on:
  push:
    branches:
      - master
      - develop

jobs:
  security_scan:
    needs: build  # Solo corre después de que la imagen haya sido construida
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout code
        uses: actions/checkout@v3

      - name: 🛡️ Run Trivy Scan on Docker image
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy --exit-code 1 --severity HIGH,CRITICAL ghcr.io/${{ github.repository }}/my-app:${{ github.sha }}
